from __future__ import annotations

import numpy as np
import pandas as pd


class AttributionError(RuntimeError):
    """Raised when portfolio attribution cannot be calculated safely."""


def build_daily_attribution(
    returns: pd.DataFrame,
    weights_history: pd.DataFrame,
    *,
    turnover: pd.Series | None = None,
    transaction_cost_bps: float = 0.0,
) -> pd.DataFrame:
    """Build daily asset-level portfolio return contributions.

    Portfolio weights calculated at a rebalance date are applied
    to subsequent daily returns until the next rebalance.

    When turnover and transaction costs are supplied, trading
    costs appear as their own attribution column.

    The asset contribution columns plus transaction costs should
    reconcile to the portfolio return generated by the backtest.
    """

    if returns.empty:
        raise ValueError(
            "Returns cannot be empty."
        )

    if weights_history.empty:
        raise ValueError(
            "Weights history cannot be empty."
        )

    if transaction_cost_bps < 0:
        raise ValueError(
            "transaction_cost_bps cannot be negative."
        )

    returns = returns.sort_index()

    weights_history = (
        weights_history
        .sort_index()
    )

    assets = (
        weights_history
        .columns
        .tolist()
    )

    missing_assets = set(
        assets
    ).difference(
        returns.columns
    )

    if missing_assets:
        raise AttributionError(
            "Returns are missing assets: "
            f"{sorted(missing_assets)}"
        )

    if not np.allclose(
        weights_history.sum(axis=1),
        1.0,
        atol=1e-6,
    ):
        raise AttributionError(
            "Portfolio weights must sum to 1 "
            "at every rebalance."
        )

    if (
        weights_history
        < -1e-6
    ).any().any():
        raise AttributionError(
            "Portfolio weights contain "
            "materially negative values."
        )

    if turnover is not None:
        turnover = (
            turnover
            .reindex(
                weights_history.index
            )
            .fillna(0.0)
            .astype(float)
        )

        if (
            turnover < -1e-8
        ).any():
            raise AttributionError(
                "Turnover cannot be negative."
            )

    contribution_columns = (
        assets
        + ["transaction_cost"]
    )

    attribution = pd.DataFrame(
        0.0,
        index=returns.index,
        columns=contribution_columns,
    )

    rebalance_dates = (
        weights_history
        .index
        .tolist()
    )

    cost_rate = (
        transaction_cost_bps
        / 10_000.0
    )

    for position, rebalance_date in enumerate(
        rebalance_dates
    ):
        weights = (
            weights_history
            .loc[rebalance_date]
            .reindex(assets)
        )

        if position + 1 < len(
            rebalance_dates
        ):
            next_rebalance = (
                rebalance_dates[
                    position + 1
                ]
            )

            holding_returns = (
                returns.loc[
                    (
                        returns.index
                        > rebalance_date
                    )
                    & (
                        returns.index
                        <= next_rebalance
                    ),
                    assets,
                ]
            )

        else:
            holding_returns = (
                returns.loc[
                    returns.index
                    > rebalance_date,
                    assets,
                ]
            )

        if holding_returns.empty:
            continue

        asset_contributions = (
            holding_returns
            .mul(
                weights,
                axis=1,
            )
        )

        attribution.loc[
            holding_returns.index,
            assets,
        ] = asset_contributions

        if (
            position > 0
            and turnover is not None
            and transaction_cost_bps > 0
        ):
            trade_cost = (
                turnover.loc[
                    rebalance_date
                ]
                * cost_rate
            )

            first_holding_date = (
                holding_returns
                .index[0]
            )

            attribution.loc[
                first_holding_date,
                "transaction_cost",
            ] = -trade_cost

    active_rows = (
        attribution[
            assets
        ]
        .abs()
        .sum(axis=1)
        > 0
    )

    attribution = attribution.loc[
        active_rows
    ].copy()

    attribution[
        "portfolio_return"
    ] = attribution.sum(
        axis=1
    )

    return attribution


def build_monthly_attribution(
    daily_attribution: pd.DataFrame,
) -> pd.DataFrame:
    """Aggregate daily contributions into monthly arithmetic contributions."""

    if daily_attribution.empty:
        raise ValueError(
            "Daily attribution cannot be empty."
        )

    contribution_columns = [
        column
        for column
        in daily_attribution.columns
        if column
        != "portfolio_return"
    ]

    monthly = (
        daily_attribution[
            contribution_columns
        ]
        .resample("ME")
        .sum()
    )

    monthly[
        "portfolio_return"
    ] = monthly.sum(
        axis=1
    )

    return monthly


def build_attribution_summary(
    daily_attribution: pd.DataFrame,
) -> pd.DataFrame:
    """Summarize total arithmetic contribution by source."""

    if daily_attribution.empty:
        raise ValueError(
            "Daily attribution cannot be empty."
        )

    contribution_columns = [
        column
        for column
        in daily_attribution.columns
        if column
        != "portfolio_return"
    ]

    total_contribution = (
        daily_attribution[
            contribution_columns
        ]
        .sum()
    )

    average_daily_contribution = (
        daily_attribution[
            contribution_columns
        ]
        .mean()
    )

    positive_days = (
        daily_attribution[
            contribution_columns
        ]
        .gt(0)
        .sum()
    )

    negative_days = (
        daily_attribution[
            contribution_columns
        ]
        .lt(0)
        .sum()
    )

    summary = pd.DataFrame(
        {
            "total_contribution": (
                total_contribution
            ),
            "average_daily_contribution": (
                average_daily_contribution
            ),
            "positive_days": (
                positive_days
            ),
            "negative_days": (
                negative_days
            ),
        }
    )

    summary.index.name = "source"

    return summary


def reconciliation_error(
    attributed_returns: pd.Series,
    portfolio_returns: pd.Series,
) -> float:
    """Return the largest absolute daily attribution mismatch."""

    comparison = pd.concat(
        [
            attributed_returns.rename(
                "attributed"
            ),
            portfolio_returns.rename(
                "portfolio"
            ),
        ],
        axis=1,
    ).dropna()

    if comparison.empty:
        raise AttributionError(
            "No overlapping observations "
            "available for reconciliation."
        )

    difference = (
        comparison[
            "attributed"
        ]
        - comparison[
            "portfolio"
        ]
    )

    return float(
        difference
        .abs()
        .max()
    )